### ISSUE TITLE
Use a static site generator like `mkdocs`

### ISSUE THREAD

**Issue by shivanshu-semwal** [lyudaio/cheatsheets#1]
You can use a static site generator like mkdocs <https://squidfunk.github.io/mkdocs-material/>.

It follows the directory structure, no need to change the structure or add any front matter, just move all the folder to a `docs` folder and create `config.yaml` file.

<https://github.com/marketplace/actions/deploy-mkdocs> you can use this github action to deploy the site to github pages.

Or you can use some other static site generator which use the directory structure.

**Comment by lyudaio** [comment]
I have set up a git sync wiki here that automatically updates. 😀 

https://cheatsheets.lyuda.io/
